default: &default
  adapter: mysql2
  encoding: utf8
  port:     <%= ENV.fetch('DATABASE_PY_PORT', 3306) %>
  username: <%= ENV['DATABASE_PY_USERNAME'] %>
  password: <%= ENV['DATABASE_PY_PASSWORD'] %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch('DATABASE_PY_HOST', 'localhost') %>
  database: <%= ENV.fetch('DATABASE_PY_NAME', 'prokat') %>

test:
  <<: *default
  host: <%= ENV.fetch('DATABASE_PY_HOST', 'localhost') %>
  database: <%= ENV.fetch('DATABASE_PY_NAME', 'prokat') %>

production:
  <<: *default
  host: <%= ENV['DATABASE_PY_HOST'] %>
  database: <%= ENV['DATABASE_PY_NAME'] %>
