default: &default
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DATABASE_PS_NAME'] %>
  port:     <%= ENV.fetch('DATABASE_PS_PORT', 3306) %>
  username: <%= ENV['DATABASE_PS_USERNAME'] %>
  password: <%= ENV['DATABASE_PS_PASSWORD'] %>

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV.fetch('DATABASE_PS_HOST', 'localhost') %>

test:
  <<: *default
  host: <%= ENV.fetch('DATABASE_PS_HOST', 'localhost') %>

production:
  <<: *default
  host: <%= ENV['DATABASE_PS_HOST'] %>
