
name: Rent-auto

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6.3
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.3
        
    - name: Install PostgreSQL 11 and MySQL clients
      run: |
        sudo apt-get update
        sudo apt-get install alien
        sudo apt-get -yqq install libpq-dev
        sudo apt-get install libmysqlclient-dev
        
    - name: Build and test with Rake
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        echo "gem: --no-ri --no-rdoc" >> ~/.gemrc
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rails db:setup
        bundle exec rake
